config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:show]
  resources :posts, only: [:index, :show, :create] do
    resources :comments, only: [:create]
  end

  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :postcategories, dependent: :destroy
  has_many :categories, through: :postcategories
  
  def save_categories(tags)
    current_tags = self.categories.pluck(:name) unless self.categories.nil?
    new_tags = tags - current_tags

    new_tags.each do |new_name|
      postcategory = Category.find_or_create_by(name:new_name)
      self.categories << postcategory
    end
  end
  
  scope :from_category, -> (category_id)  { where(id: post_ids =  Postcategory.where(category_id: category_id).select(:post_id))}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
    
    words = params[:search].to_s.gsub(/(?:[[:space:]%_])+/, " ").split(" ")
    title_query = (["title LIKE ?"] * words.size).join(" AND ")
    body_query = (["body LIKE ?"] * words.size).join(" AND ")
    content_query = (["content LIKE ?"] * words.size).join(" AND ")
    
    title_searched_posts = Post.where(title_query, *words.map { |w| "%#{w}%" })
    body_searched_posts = Post.where(body_query, *words.map { |w| "%#{w}%" })
    content_searched_comments = Comment.where(content_query, *words.map { |w| "%#{w}%" })
    content_searched_posts = content_searched_comments.map(&:post).flatten
    
    @searched_posts = (title_searched_posts + body_searched_posts + content_searched_posts).uniq
  
    if params[:category_id].present?
      @selected_category = Category.find(params[:category_id])
      @posts= Post.from_category(params[:category_id])
    else
      @posts= Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def create
    @post= current_user.posts.build(post_params)
    category_list = params[:category_list].split(",")
    if @post.save
      @post.save_categories(category_list)
      redirect_to root_path, success: "スレッドを作成しました！"
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>Forum App</h1>
<div class="header">
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
</div>

<h2>検索</h2>
<div class="header">
  <%= form_tag(root_path,:method => 'get') do %>
    <%= text_field_tag :search %>
    <p><%= submit_tag '検索', :name => nil %></p>
  <% end %>
</div>
<hr>
<h2>新規スレッド作成</h2>
<div class="container">
  <%= form_for @post do |f| %>
    <%= f.label "タイトル", class:'control-label' %>
    <%= f.text_field :title, class: 'form-control' %>
    <div class="post-tags-field">
      <%= f.label "カテゴリー", class:'control-label' %>
      <ul id="post-tags", class: 'form-control'></ul>
    </div>    
    <%= f.label "内容", class:'control-label' %>
    <%= f.text_area :body, class: 'form-control' %>
    <p><%= f.submit 'スレッド作成' %></p>
  <% end %>
</div>
<hr>
<h2>投稿スレッド一覧</h2>
<div class="container">
  <% if params[:search].present? %>
    <% @searched_posts.each do |post| %>
      <h2><a href="/posts/<%= post.id %>"><%= post.title %></a></h2>
    <% end %>
  <% else %>
    <% @posts.each do |post| %>
      <h2>
        <%= link_to post_path(post.id) do %>
          <%= post.title %>
        <% end %>
      </h2>
    <% end %>
  <% end %>
  <P><%= link_to "ホームへ戻る", posts_path %></P>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h5>
  スレッド投稿者：<a href="/users/<%= @post.user.id %>"><%= @post.user.email %></a>
</h5>
<h5>
  <div class="container">
    <% unless @post.categories.blank? %>
    含まれるカテゴリー：
        <% @post.categories.each do |category| %>
          <%= link_to category.name,root_path(category_id: category.id) %>
        <% end %>
    <% end %>
  </div>
</h5>
<h3>
  <div class="container">
    <%= @post.body %>
    <hr>
  </div>
</h3>
<div class="container">
  <div class="comments">
    <% @comments.each do |c| %>
      <div>
        <a href="/users/<%= c.user.id %>"><%= c.user.email %></a>
        <%= c.content %>
        <%= c.created_at %>
        <hr>
      </div>
    <% end %>
    
    <%= form_for [@post, @comment] do |f| %>
      <%= f.text_area :content, size: "80x5" %>
      <br>
      <p><%= f.submit '書き込む' %></p>
    <% end %>
    
    <P><%= link_to "ホームへ戻る", posts_path %></P>
  </div>
</div>